name:                gltf-builder
version:             0.1.0.0
github:              "githubuser/gltf-builder"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gltf-builder#readme>

dependencies:
- base >= 4.7 && < 5
- binary
- bytestring
- containers
- text
- transformers
- vector
- aeson # https://hackage.haskell.org/package/aeson
- aeson-pretty
- base64
- directory
- data-default
- extra
- filepath
- lens
- linear
- mime-types
- network-uri
- wreq
- validity

default-extensions:
- OverloadedStrings
- DuplicateRecordFields
- DisambiguateRecordFields # https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/disambiguate_record_fields.html
- NamedFieldPuns

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gltf-builder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gltf-builder

tests:
  gltf-builder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gltf-builder
    - hspec
    - hspec-discover
